version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    security-updates-only: true

  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
    security-updates-only: true